### ISSUE TITLE
Drag and drop from file manager does not work on Flatpak 

### ISSUE THREAD

**Issue by pWn574R** [Taiko2k/Tauon#1153]
Hello, the drag-and-drop functionality in the flatpak does not seem to work while using Dolphin on KDE plasma 6. I am using fedora

**Comment by YSqQrH0zurvGmYfF** [comment]
Hello, I had same issue with flatpaked Telegram. The app only has permission to read files from the "Downloads" and "Music" folders, so drag-and-drop doesn't work elsewhere. To fix this problem, you need to give permission to the selected folder (or just "Home") in the flatpak app settings. Since you are using KDE, you can do this through Settings. (Also you can use Flatseal or default CLI)

**Comment by Taiko2k** [comment]
Yeah it's likely an issue of needing to add permission. 

Though Tauon should show a warning message when this happens, not sure why it's not showing.

**Comment by pWn574R** [comment]
Thanks! I changes the permissions and it works as expected now
