### ISSUE TITLE
MP3s tagged with Mp3tag on Windows have a missing Year field

### ISSUE THREAD

**Issue by wavetro** [Taiko2k/Tauon#1185]
On Windows 11, use the latest [Mp3tag](https://www.mp3tag.de/en/) to tag a Year (such as "2023-07-11") on an MP3 and then load that same file in Tauon on Linux. The "Year" field will be missing, possibly due to not supporting a new spec of MP3 tagging. This issue has NOT been happening with any MP3s I've been tagging with the latest [Puddletag](https://docs.puddletag.net/) flatpak on Linux. MP3s I tagged on Windows that are also older than a year are also unaffected, which is why I think this is Tauon missing support for a new MP3 tagging spec. 

I'm using the Tauon flatpak v.7.8.0 on Zorin OS 17, which is basically a re-skinned Ubuntu 22.04 LTS. Please take a look if you can!

**Comment by C0rn3j** [comment]
That would probably be on [Mutagen](https://github.com/quodlibet/mutagen) - 

Can you retest 7.8.3, and if it still happens, link such a broken file - ideally something copyright free?

**Comment by wavetro** [comment]
Testing on 7.8.3 and this is unfortunately still happening.

Broken song can be found [HERE](https://mega.nz/file/E2Mgka6b#sz6sx2kM7lMl-cye7w48oY11Qq56chCAiPoiPRgIA6U) and looks like this:
![image](https://github.com/user-attachments/assets/efce04b1-f7bd-474a-95a4-84f3ca3ef05d)

Working song can be found [HERE](https://mega.nz/file/53UQFaxR#zQpeFn6b6T-CrOTZSvE9984Nc0kOcc0WX4Xurk71bmc) and looks like this:
![image](https://github.com/user-attachments/assets/03b87c04-2bc7-456a-8b38-98815ea55f06)

**Comment by C0rn3j** [comment]
Tauon detects both dates fine on these files, can you reproduce it on current master (7.9.0)?

If so I would suspect you have some dated version of mutagen that you're loading.

If you're on Windows you will need this PR - https://github.com/Taiko2k/Tauon/pull/1352

![image](https://github.com/user-attachments/assets/18a8802d-cc34-4ec4-a070-0554ff065eeb)

![image](https://github.com/user-attachments/assets/f3711d00-8277-466d-9250-873ad9891bd5)

**Comment by wavetro** [comment]
I would love to try this new build, but I can't seem to find where to download or compile it. Where can I find v7.9.0? I'm on Linux Mint 22, which is essentially Ubuntu 24.04 LTS.

**Comment by C0rn3j** [comment]
You can go to the main page, click the checkmark next to the latest commit, open the CI Action for your OS, click Summary and a download will be there.

Which for Linux is currently this one - https://github.com/Taiko2k/Tauon/actions/runs/12450411103

Ironically, the Linux pyinstaller prebuilt images are currently in the worst state compared to macOS/Windows and you'd probably be better to run it on your own for now.

If you have issues with the prebuilts, you can leave a comment here if your issue is missing - https://github.com/Taiko2k/Tauon/issues/1315

Instructions to build manually(which should work fine) are here - https://github.com/Taiko2k/Tauon/wiki/Building

If you want the very bleeding-edge prebuilts you can grab the one from latest commit in my open PR - https://github.com/Taiko2k/Tauon/pull/1354

**Comment by wavetro** [comment]
Yes, I can confirm the dates are now displaying correctly on all of my MP3s on the v7.9.0 build from #1354. Thank you!
