### ISSUE TITLE
Track ratings don't import from mp3

### ISSUE THREAD

**Issue by mirrorcult** [Taiko2k/Tauon#1189]
![image](https://github.com/user-attachments/assets/0fa27fac-a2bf-404f-a2cc-7037c7386097)

- windows 10
- tauon 7.8.0
- track ratings were tagged using musicbee

previously used musicbee, switching to tauon to prepare for a linux switch -- looks like whatever windows reads for the "rating" field is what musicbee uses, but doesn't import here. also doesn't work with flacs/opus but I see a separate issue for that (#1027). tried rescanning tags a couple times, reimporting etc but doesnt work.

**Comment by mirrorcult** [comment]
not a windows thing, just did a fresh import on nixos and it didnt work either

**Comment by Taiko2k** [comment]
Tauon reads these on scan but doesn't *apply* them automatically. To apply them you need to go MENU > Database then select either import FMPS or import POPM ratings.

To write ratings to tags (on change only) you need to go MENU > Settings > "Open config file" then set "write-ratings-to-tag" to "true", then save.

Its designed this way because I have an aversion of tag ratings.

**Comment by mirrorcult** [comment]
makes sense, I'll try it tomorrow morning

**Comment by mirrorcult** [comment]
yep, that works fine
