### ISSUE TITLE
[Bug] Default playlist disappeared

### ISSUE THREAD

**Issue by demeralde** [Taiko2k/Tauon#375]
I never deleted it, so I'm not sure how this happened (unless I somehow did so unintentionally?) 

It seemed to happen after setting the flatpak permission to Picard.

Is there a way to recreate this playlist? IMO it shouldn't be able to be deleted, since it's what you use to view your entire library.

**Comment by dspacejs** [comment]
Looks like creating a new playlist automatically imported my entire music library back. Not sure what happened here.

**Comment by Taiko2k** [comment]
You might have accidentality deleted it, or dragged it off the top panel, try check the playlist list (left side panel) see if its there but just unpinned?

**Comment by dspacejs** [comment]
@Taiko2k I don't see it anywhere, how do I see the unpinned playlists?

**Comment by Taiko2k** [comment]
Right click top-corner button, `Playlists + Queue`. That should list all playlists.

**Comment by dspacejs** [comment]
@Taiko2k yeah, that's the view I was on. It didn't show, so the playlist must have been deleted. I don't recall doing this myself, so I assume it was a bug.

**Comment by awsms** [comment]
I just had this issue for the third time since I'm using Tauon, and I found a workaround.
Search (with the global search) for a song that was in the now 'invisible' playlist (it's not actually deleted), click on it, and now the playlist will show up.
Note that you won't be able to go back again to the playlist without doing this workaround as the playlist won't appear in the top menu anymore.

![Screenshot from 2021-06-10 10-07-05](https://user-images.githubusercontent.com/48278661/121488712-a21ca200-c9d3-11eb-9d1e-444d155ba252.png)

**Comment by Taiko2k** [comment]
This is just the pin/unpin system right? If you drag a playlist off the panel it disappears. You need to go to the playlist panel to restore it.

**Comment by C0rn3j** [comment]
Closing since this seems to be a confusion about pinned tabs and there was no response for 3 years.

![image](https://github.com/user-attachments/assets/99c04b12-0bf2-4a78-8127-69c10b40211e)

To be fair I had no clue myself they were pinned tabs until I read through this issue, and now I noticed that pinned tabs are noted in the left hand menu.

Maybe it'd be relevant to improve the UI/UX a bit in that regard, something to keep in mind for #1343
