### ISSUE TITLE
Import favorites and playlist from Jellyfin

### ISSUE THREAD

**Issue by wyndon** [Taiko2k/Tauon#554]
Currently, Tauon doesn't import Jellyfin playlists and favorited songs. It would be cool if Tauon could import and update them on Jellyfin when adding new songs.
It would save the hassle of having to export the database and importing it on a new computer.

Now doing this will confuse some things : how to differentiate a playlist from Tauon and one from Jellyfin ? It would be needed to do some kind of separation.

I'm asking this for Jellyfin, but I *guess* that other supported services could benefit from this as well.

Would this be possible/is in the scope of this project ?

**Comment by Taiko2k** [comment]
It could work like the Spotify playlist support works, where you can import playlists from a menu, and manually push/pull changes using the tab menu. It otherwise works like a normal playlist, just normal tracks put in it won't sync.

It is a feature I think is within scope, but it's a fair bit of work and is kind of low priority for me.

**Comment by jibsaramnim** [comment]
Having created playlists synced to/from Jellyfin would be amazing for me, as it would allow me to really seamlessly keep listening to my favorite albums regardless of which computer I'm working on that day. Though I understand this might be a bigger undertaking. Is there already (part of) this concept somewhere in the playlist related code, or would this require a bunch of work from the ground up?

**Comment by Taiko2k** [comment]
Most doable would be a push/pull model, it would be explicitly manual and per playlist, so no auto sync, and you would have to select playlists one at a time to initially import. Would that be acceptable?

**Comment by jibsaramnim** [comment]
A little background: What I'm currently doing for local playlists is that as soon as I create one I edit its generator and add `s"" tn auto` to it. I also have `auto` added to my Jellyfin "playlist", so whenever I open the main Jellyfin playlist it automatically fetches whatever may have changed from Jellyfin, and whenever I open a playlist after this, they too automatically fetch whatever new albums might've come in from that particular artist the playlist is for.

Would with this proposal the `auto` option be usable to automatically fetch new changes from said playlist? If so, that could end up working quite nicely then.

Of course it would be even nicer if it could create a playlist on Jellyfin's side from the app (whether automatically or after a push to do so), that would make it quite a powerful combination indeed.

_(Small side note in what I shared above; the `s""` somehow seems to be required or otherwise when I refresh a playlist it just goes fully blank. This is with my entire library being served from Jellyfin, I have no local audio files)_

**Comment by Taiko2k** [comment]
I've now committed playlist download / upload functionality. Ill write a detailed guide closer to release.

**Comment by wyndon** [comment]
> I've now committed playlist download / upload functionality. Ill write a detailed guide closer to release.

Seems to work good. Thanks!

Are favorites sync also planned?

**Comment by Taiko2k** [comment]
> Are favorites sync also planned?

That has already been implemented for a while. Is it not working for you? 

(Small related bug introduced in recent commit, committed a fix now)

**Comment by wyndon** [comment]
> > Are favorites sync also planned?
> 
> That has already been implemented for a while. Is it not working for you?
> 
> (Jellyfin -> Tauon sync only happens on main library import/regenerate, Tauon -> Jellyfin happens immediately)
> 
> (Small related bug introduced in recent commit, committed a fix now)

Sorry, I may have badly worded this. Favorites sync work as intended, but in Jellyfin, you have the ability to actually play songs only through your favorites, kinda like a playlist. So I was hoping to have all my favorites synced to a playlist in Tauon.

**Comment by Taiko2k** [comment]
You could do that through tauons normal features though right? Create new playlist > edit generator > enter `a l auto`

**Comment by edgar-vincent** [comment]
@Taiko2k Should this issue be closed?

**Comment by C0rn3j** [comment]
Closing since it seems to be implemented.
